name: simple flows

 

on:

  push:

    branches: [ "main" ]

    

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Run a one-line script

        run: echo Hello, world!

      - name: Run a multi-line script

        run: |

          echo Add other actions to build,

          echo test, and deploy your project.

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:

      - name: Check Uptime

        run: uptime

      - name: Cpu info

        run: nproc

      - name: kernel info 

        run: uname -r

      - name: check memory

        run: free -m

      - name: check hard drive

        run: lsblk

      - name: os version 

        run: cat /etc/os-release
     
    




